apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: asg-autotagger
spec:
  successfulJobsHistoryLimit: 1
  schedule: "*/60 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: "{{ .Release.Name }}"
          labels:
            app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
            app.kubernetes.io/instance: {{ .Release.Name | quote }}
            helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        spec:
          containers:
            - name: asg-pod-container
              image: banst/awscli:1.18.76
              command: ['sh','-c' ,"aws configure set default.region {{ .Values.autotagger.clusterregion }}; results=$(aws autoscaling describe-auto-scaling-groups | jq -c '.AutoScalingGroups[]|  select(.AutoScalingGroupName |  contains (\"{{ .Values.autotagger.clustername }}\"))| .AutoScalingGroupName ') ;for resourceId in $results;do  aws autoscaling create-or-update-tags --tags ResourceId=$resourceId,ResourceType=auto-scaling-group,Key=k8s.io/cluster-autoscaler/enabled,Value=yes,PropagateAtLaunch=true ResourceId=$resourceId,ResourceType=auto-scaling-group,Key=k8s.io/cluster-autoscaler/{{ .Values.autotagger.clustername }},Value=yes,PropagateAtLaunch=true; done; date;"]
          restartPolicy: OnFailure
