#!/usr/bin/env bash
# ------------------------------------------------------------------------------
# Retrieves the kubeconfig for a given clusterId and writes it out in the form:
# kubeconfig-${clusterId}
# ------------------------------------------------------------------------------

source $HOME/.concord/concord.bash
[ -z "$1" ] && echo && echo "You must provide the clusterId from your clusterRequest." && echo && exit
concord_kubeconfig "kubeconfig-${1}"
